# conda env create
# source activate insight
name: insight
dependencies:
- python=3.5 # for python version on binder
- jinja2
- pandas
- numpy
- scikit-learn
- scikit-image
- bokeh=0.11.0
- requests
- xlrd
- pip: [traitlets,multipledispatch,geopy,ipywidgets]
